import Ajv2020 from'ajv/dist/2020.js';const publisher=Object.freeze({name:'SHAR Production',website:'https://sharprod.com/'}),draft='https://json-schema.org/draft/2020-12/schema',date='^\\d{4}-\\d{2}-\\d{2}$',datetime='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$',sha='^[a-f0-9]{64}$',locale='^[a-z]{2}(?:-[A-Z]{2})?$';
const make=(id,en,ru,summaryEn,summaryRu,properties,required,valid,invalid)=>({id,title:{en,ru},summary:{en:summaryEn,ru:summaryRu},publisher,schema:{$schema:draft,$id:`https://sharprod.com/schemas/${id}.schema.json`,title:`SHAR Production ${en} Contract`,type:'object',additionalProperties:false,properties,required},valid,invalid});
export const contractCatalog=[
make('deliverable-manifest','Deliverable Manifest','Манифест материалов','Files, locales and immutable checksums.','Файлы, локали и неизменяемые контрольные суммы.',{project_id:{type:'string',pattern:'^[a-z0-9-]+$'},deliverables:{type:'array',minItems:1,items:{type:'object',additionalProperties:false,required:['path','locale','sha256'],properties:{path:{type:'string',pattern:'^[^./][^\\\\]*$'},locale:{type:'string',pattern:locale},sha256:{type:'string',pattern:sha}}}}},['project_id','deliverables'],{project_id:'synthetic-campaign',deliverables:[{path:'masters/final.mov',locale:'en-US',sha256:'a'.repeat(64)}]},{project_id:'synthetic-campaign',deliverables:[]}),
make('shot-list','Shot List','Шот-лист','Structured shots, duration and capture status.','Структурированные планы, длительность и статус съёмки.',{project_id:{type:'string'},shots:{type:'array',minItems:1,items:{type:'object',required:['shot_id','duration_seconds','status'],properties:{shot_id:{type:'string'},duration_seconds:{type:'number',exclusiveMinimum:0},status:{enum:['planned','captured','approved']}}}}},['project_id','shots'],{project_id:'synthetic-film',shots:[{shot_id:'S001',duration_seconds:4.5,status:'planned'}]},{project_id:'synthetic-film',shots:[{shot_id:'S001',duration_seconds:0,status:'planned'}]}),
make('privacy-safe-call-sheet','Privacy-safe Call Sheet','Call sheet без персональных данных','Role-based calls without personal names or contacts.','Вызовы по ролям без имён и личных контактов.',{production_date:{type:'string',pattern:date},timezone:{type:'string',pattern:'^[A-Za-z_]+/[A-Za-z_]+$'},units:{type:'array',minItems:1,items:{type:'object',additionalProperties:false,required:['role_ref','call_time'],properties:{role_ref:{type:'string',pattern:'^role-[a-z0-9-]+$'},call_time:{type:'string',pattern:'^([01]\\d|2[0-3]):[0-5]\\d$'}}}}},['production_date','timezone','units'],{production_date:'2026-09-06',timezone:'Europe/Moscow',units:[{role_ref:'role-camera-a',call_time:'08:30'}]},{production_date:'2026-09-06',timezone:'Europe/Moscow',units:[{role_ref:'Alex',call_time:'25:00'}]}),
make('rights-window','Rights Window','Окно прав','Territory and bounded start/end timestamps.','Территория и ограниченные даты начала/окончания.',{asset_id:{type:'string'},territory:{type:'string',pattern:'^(?:[A-Z]{2}|WORLD)$'},starts_at:{type:'string',pattern:date},ends_at:{type:'string',pattern:date}},['asset_id','territory','starts_at','ends_at'],{asset_id:'asset-synthetic-01',territory:'WORLD',starts_at:'2026-09-06',ends_at:'2027-09-06'},{asset_id:'asset-synthetic-01',territory:'world'}),
make('localization-matrix','Localization Matrix','Матрица локализации','Locales and required audio/subtitle outputs.','Локали и требуемые аудио/субтитры.',{master_id:{type:'string'},locales:{type:'array',minItems:1,items:{type:'object',required:['tag','audio','subtitles'],properties:{tag:{type:'string',pattern:locale},audio:{type:'boolean'},subtitles:{type:'boolean'}}}}},['master_id','locales'],{master_id:'master-synthetic',locales:[{tag:'ru-RU',audio:true,subtitles:true}]},{master_id:'master-synthetic',locales:[{tag:'russian',audio:true,subtitles:true}]}),
make('approval-event-log','Approval Event Log','Журнал согласований','Timestamped stages and explicit decisions.','Этапы с timestamp и явными решениями.',{subject_id:{type:'string'},events:{type:'array',minItems:1,items:{type:'object',required:['at','stage','decision'],properties:{at:{type:'string',pattern:datetime},stage:{enum:['brief','creative','offline','master']},decision:{enum:['approved','changes_requested','rejected']}}}}},['subject_id','events'],{subject_id:'synthetic-master',events:[{at:'2026-09-06T10:00:00Z',stage:'master',decision:'approved'}]},{subject_id:'synthetic-master',events:[{at:'today',stage:'master',decision:'yes'}]}),
make('checksum-inventory','Checksum Inventory','Реестр контрольных сумм','SHA-256 inventory with safe relative paths.','Реестр SHA-256 с безопасными относительными путями.',{algorithm:{const:'sha256'},files:{type:'array',minItems:1,items:{type:'object',required:['path','sha256'],properties:{path:{type:'string',pattern:'^[^./][^\\\\]*$'},sha256:{type:'string',pattern:sha}}}}},['algorithm','files'],{algorithm:'sha256',files:[{path:'masters/final.mov',sha256:'b'.repeat(64)}]},{algorithm:'md5',files:[]}),
make('retention-policy','Retention Policy','Политика хранения','Asset class, retention date and terminal action.','Класс актива, дата хранения и конечное действие.',{asset_class:{enum:['working','master','legal','proxy']},retain_until:{type:'string',pattern:date},terminal_action:{enum:['review','archive','delete']}},['asset_class','retain_until','terminal_action'],{asset_class:'master',retain_until:'2031-09-06',terminal_action:'archive'},{asset_class:'master',terminal_action:'keep'}),
make('vendor-bid-comparison','Vendor Bid Comparison','Сравнение предложений подрядчиков','Pseudonymous bids with currency, total and scope score.','Псевдонимные предложения с валютой, суммой и scope score.',{currency:{type:'string',pattern:'^[A-Z]{3}$'},bids:{type:'array',minItems:2,items:{type:'object',required:['vendor_ref','total','scope_score'],properties:{vendor_ref:{type:'string',pattern:'^vendor-[a-z0-9-]+$'},total:{type:'number',minimum:0},scope_score:{type:'integer',minimum:0,maximum:100}}}}},['currency','bids'],{currency:'RUB',bids:[{vendor_ref:'vendor-alpha',total:100000,scope_score:82},{vendor_ref:'vendor-beta',total:120000,scope_score:91}]},{currency:'rub',bids:[{vendor_ref:'Real Company',total:-1,scope_score:101}]}),
make('privacy-safe-incident-log','Privacy-safe Incident Log','Журнал инцидентов без персональных данных','Operational severity and status without direct personal data.','Операционный severity/status без прямых персональных данных.',{incident_id:{type:'string',pattern:'^incident-[a-z0-9-]+$'},severity:{enum:['low','medium','high','critical']},occurred_at:{type:'string',pattern:datetime},status:{enum:['open','contained','resolved']},personal_data_present:{const:false}},['incident_id','severity','occurred_at','status','personal_data_present'],{incident_id:'incident-synthetic-01',severity:'medium',occurred_at:'2026-09-06T11:00:00Z',status:'contained',personal_data_present:false},{incident_id:'incident-synthetic-01',severity:'urgent',personal_data_present:true})
];
const ajv=new Ajv2020({strict:false});const validators=new Map(contractCatalog.map(c=>[c.id,ajv.compile(c.schema)]));export function validateContract(id,input){const fn=validators.get(id);if(!fn)throw new Error(`Unknown contract: ${id}`);const valid=fn(input);return{valid,errors:valid?[]:structuredClone(fn.errors)}}
